# Generated by Django 4.0.1 on 2023-02-24 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('reg_time', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
