# Generated by Django 4.0.1 on 2023-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_info', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('picture', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
