# Generated by Django 4.0.1 on 2023-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizenum', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sizeguide',
            },
        ),
    ]
