# Generated by Django 4.0.1 on 2023-04-21 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0008_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('money', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('money', models.FloatField()),
                ('type', models.IntegerField()),
                ('bank', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.AddField(
            model_name='shipping',
            name='member_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
