# Generated by Django 4.0.1 on 2023-04-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0009_orderdetail_orders_payment_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
    ]
