# Generated by Django 4.0.1 on 2023-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0012_rename_order_shipping_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
