# Generated by Django 4.0.1 on 2023-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0013_alter_shipping_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=255)),
                ('cate_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_id',
            field=models.IntegerField(default=1),
        ),
    ]
