# Generated by Django 4.0.1 on 2023-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0014_subcategories_product_sub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(default=1)),
                ('product_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'rate',
            },
        ),
    ]
