# Generated by Django 4.0.1 on 2023-04-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0017_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='appadmin.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
